name: Build OpenResty with custom dynamic modules for Ubuntu/Debian

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Modules
    runs-on: ubuntu-20.04

    steps:
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: repos
          key: ${{ runner.os }}-repos
        
      - name: Checkout OpenResty-Packaging repository
        uses: actions/checkout@v4
        with:
          repository: openresty/openresty-packaging
          path: repos/openresty-packaging
          ref: '64c5dff64f5777c14ec17dab68edae935ba9e142'
          
      - name: Checkout nginx-dav-ext-module
        uses: actions/checkout@v4
        with:
          repository: arut/nginx-dav-ext-module
          path: repos/nginx-dav-ext-module
          ref: 'f5e30888a256136d9c550bf1ada77d6ea78a48af'

      - name: Install dependencies
        run: |
          wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list
          sudo apt update
          sudo apt upgrade
          sudo apt install wget gnupg ca-certificates libtemplate-perl debhelper systemtap-sdt-dev perl gnupg curl make build-essential dh-make bzr-builddeb libxml2-dev libxslt-dev
    
      - name: Patch packaging rules
        working-directory: repos/openresty-packaging/deb
        run: |
          sed -i "s|-j\$(NJBS)|-j\$(NJBS) --add-dynamic-module=$GITHUB_WORKSPACE/repos/nginx-dav-ext-module|g" openresty/debian/rules
          cat openresty/debian/rules
          
      - name: Compile
        continue-on-error: true
        working-directory: repos/openresty-packaging/deb
        run: make openresty-build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Modules
          path: repos/openresty-packaging/deb/openresty/build/nginx-*/objs/*.so
          if-no-files-found: error
          retention-days: 90
